# -*- coding: utf-8 -*-
"""1_ml_ass_B_part.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X6eXnMwlMU0zQuyRWb3n9c5GvHv0XnDY

#Mark prediction and error analysis respective to your CRN 023-348
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


# Load the exact dataset provided
url = "https://raw.githubusercontent.com/dharmdevchai/datasets/main/marks_prediction/behavioral_indicators_internal_marks.csv"
df = pd.read_csv(url)

print("Dataset Loaded Successfully. Rows:", df.shape)

df.info()

df.isnull().sum()

import seaborn as sns
import matplotlib.pyplot as plt
for i in df.select_dtypes(include="number").columns:
  sns.boxplot(data=df, x=i)
  plt.show()

def wisker(col):
  q1, q3=np.percentile(col,[25,75])
  #calculate inter quartile range
  iqr=q3-q1
  lw=q1-1.5*iqr
  uw=q3+1.5*iqr
  return lw, uw

dfc=df.copy()

for i in df.select_dtypes(include="number").columns:
  lw, uw = wisker(dfc[i])
  # cap lower outliers
  dfc[i] = np.where(dfc[i] < lw, lw, dfc[i])
  # cap upper outliers
  dfc[i] = np.where(dfc[i] > uw, uw, dfc[i])

for i in dfc.select_dtypes(include="number").columns:
  sns.boxplot(data=dfc, x=i)
  plt.show()

dfc.shape

forbidden_cols = ['CRN', 'Final_Theory_Marks_30', 'Final_Practical_Marks_20']

X = dfc.drop(columns=forbidden_cols + ['Total_Internal_Marks_50'])
y = dfc['Total_Internal_Marks_50']

X.isnull().sum()

print("Features Used for Training:", X.columns)

# spliting data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training Matrix Size: {X_train.shape}")
print(f"Testing Matrix Size: {X_test.shape}")

# trainging model
model = LinearRegression()
model.fit(X_train, y_train)

# generating test prediction
y_pred = model.predict(X_test)


# Calculating Sum of Absolute Errors (SAE)
sae = np.sum(np.abs(y_test - y_pred))
mae = np.mean(np.abs(y_test - y_pred))

print(f"Sum of Absolute Errors (SAE): {sae:.4f}")
print(f"Mean Absolute Error (MAE): {mae:.4f}")

# Extracting own record for roll number 023-348
my_record = dfc[dfc['CRN'] == '023-348'] # Use dfc here

# Isolating feature vectors
# Ensure 'Total_Internal_Marks_50' is not in my_X for prediction, as it's the target.
# Also use the same feature set as X.
my_X = my_record.drop(columns=forbidden_cols + ['Total_Internal_Marks_50'])
my_actual_y = my_record['Total_Internal_Marks_50'].values[0]

# Perform model inference
my_pred_y = model.predict(my_X)[0]
my_absolute_error = abs(my_actual_y - my_pred_y)

print(f"--- Roll Number 023-348 Results ---")
print(f"Actual Internal Marks: {my_actual_y}")
print(f"Predicted Internal Marks: {my_pred_y:.4f}")
print(f"Absolute Error for Your Record: {my_absolute_error:.4f}")

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MODEL EVALUATION METRICS")
print(f"Mean Absolute Error (MAE)      : {mae:.4f}")
print(f"Mean Squared Error (MSE)       : {mse:.4f}")
print(f"Root Mean Squared Error (RMSE) : {rmse:.4f}")
print(f"R-squared (R2) Score           : {r2:.4f}")