# -*- coding: utf-8 -*-
"""heart_failure_rediction_ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vy_4YRLvOqHDyqh0nVbcxdgCFp-gYwMv

#Step 1: Import Libraries & Load Dataset
"""

#Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Loading the uploaded dataset
url = "https://raw.githubusercontent.com/dharmdevchai/datasets/main/heart_failure_prediction/heart.csv"
df = pd.read_csv(url)

print("Dataset Loaded Successfully. Rows:", df.shape)
print(df.info())
print(df.head())

"""#Step 2: Exploratory Data Analysis & Preprocessing"""

# Check for missing values & duplicates
print("Missing values per column:\n", df.isnull().sum())
print("\nNumber of duplicate rows:", df.duplicated().sum())

# Handle duplicates if any exist
df = df.drop_duplicates()

# Visualize the Target Variable Distribution
plt.figure(figsize=(5, 4))
sns.countplot(data=df, x='HeartDisease', hue='HeartDisease', palette='Set2', legend=False)
plt.title('Distribution of Heart Disease Cases')
plt.show()

# Encode Categorical Variables
categorical_cols = df.select_dtypes(include=['object']).columns
print("Categorical columns to encode:", list(categorical_cols))

le = LabelEncoder()
for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

df.head()

# Separate Features (X) and Target (y)
X = df.drop('HeartDisease', axis=1)
y = df['HeartDisease']

"""#Step 3: Train-Test Split & Feature Scaling"""

# Split data: 80% Training, 20% Testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Scale features (Crucial for SVM and kNN performance)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)



print(f"Training set size: {X_train.shape[0]} samples")
print(f"Testing set size: {X_test.shape[0]} samples")

"""#Step 4: Model Building, Evaluation, and Comparison"""

# Initialize the three baseline models
models = {
    "Support Vector Machine": SVC(kernel='rbf', random_state=42),
    "k-Nearest Neighbors": KNeighborsClassifier(n_neighbors=5),
    "Decision Tree": DecisionTreeClassifier(criterion='gini', max_depth=4, random_state=42)
}

# Dictionary to capture evaluation results
results = {}

# Train and evaluate each model
for name, model in models.items():
    # Fit model (Use scaled data for SVM and kNN, though Tree can use either)
    if name in ["Support Vector Machine", "k-Nearest Neighbors"]:
        model.fit(X_train_scaled, y_train)
        predictions = model.predict(X_test_scaled)
    else:
        model.fit(X_train, y_train)
        predictions = model.predict(X_test)

    # Metrics
    acc = accuracy_score(y_test, predictions)
    results[name] = acc

    print(f"\n================ {name} ================")
    print(f"Accuracy: {acc:.4f}")
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, predictions))
    print("\nClassification Report:")
    print(classification_report(y_test, predictions))

# Visualize Decision Tree Structure
plt.figure(figsize=(16, 8))
plot_tree(models["Decision Tree"], feature_names=X.columns, class_names=['No', 'Yes'], filled=True, rounded=True)
plt.title("Decision Tree Structure")
plt.show()

"""#Step 5: Hyperparameter Tuning (Example: Tuning the Decision Tree)"""

print("\n--- Tuning Decision Tree Parameters ---")

# Setup parameter grid
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [3, 5, 10, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Run Grid Search
grid_search = GridSearchCV(DecisionTreeClassifier(random_state=42), param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

best_dt = grid_search.best_estimator_
tuned_predictions = best_dt.predict(X_test)
tuned_acc = accuracy_score(y_test, tuned_predictions)

print("Best Parameters Found:", grid_search.best_params_)
print(f"Baseline Decision Tree Accuracy: {results['Decision Tree']:.4f}")
print(f"Tuned Decision Tree Accuracy: {tuned_acc:.4f}")

"""## Part 3: Addressing the Professor's Challenge Question

### 1. Performance Summary
To evaluate which model is best suited for clinical deployment, we aggregate the performance metrics for **Class 1 (Heart Disease Presence)** across all three trained models:

### Support Vector Machine (SVM):

Overall Accuracy: 88.59%

Class 1 Precision: 0.86

Class 1 Recall (Sensitivity): 0.94

False Negatives (Missed Cases): 6

False Positives (False Alarms): 15

### k-Nearest Neighbors (kNN):
Overall Accuracy: 89.13%

Class 1 Precision: 0.89

Class 1 Recall (Sensitivity): 0.91

False Negatives (Missed Cases): 9

False Positives (False Alarms): 11

### Decision Tree:

Overall Accuracy: 80.98%

Class 1 Precision: 0.83

Class 1 Recall (Sensitivity): 0.82

False Negatives (Missed Cases): 18

False Positives (False Alarms): 17

---
### 2. Clinical Analysis & Model Selection
Evaluate these models through a **clinical risk framework**.

#### The Deception of Accuracy
If we deploy a model based strictly on global accuracy, **k-Nearest Neighbors (89.13%)** appears to be the winner. However, in medical diagnostics, the costs of the two error types are drastically asymmetrical:
*   **False Positive (Type I Error):** Diagnosing a healthy patient with heart disease. *Clinical Cost:* Low. It leads to psychological stress and unnecessary follow-up diagnostic tests, but no physical harm.
*   **False Negative (Type II Error):** Telling a patient with heart disease that they are perfectly healthy. *Clinical Cost:* Fatal. The patient is sent home without treatment, bypassing critical intervention.

#### Why SVM is the Clinically Superior Choice
1. **Minimizing Life-Threatening Errors:** The **SVM** model minimized False Negatives to just **6 patients**, whereas kNN missed **9**, and the Decision Tree missed an unacceptable **18** patients.
2. **Maximizing Sensitivity:** SVM achieved the highest **Recall (0.94)** for the positive class. This means the SVM successfully catches 94% of all actual heart disease cases in the cohort.
3. **The Trade-Off:** To catch those extra 3 critically ill patients that kNN missed, SVM accepts a slightly higher rate of False Positives (15 vs 11). In a clinical workflow, this is a highly acceptable trade-off.

> **Conclusion:** The **Support Vector Machine (SVM)** is selected as the optimal model for clinical deployment because it prioritizes patient safety by maximizing Recall and minimizing dangerous False Negatives.

## Visualizing the Accuracy vs. Recall Paradox
"""

# Create a DataFrame of our model results
results_data = {
    "Model": ["SVM", "kNN", "Decision Tree"],
    "Accuracy": [0.8859, 0.8913, 0.8098],
    "Recall (Class 1)": [0.9400, 0.9100, 0.8200],
    "False Negatives": [6, 9, 18],
}

df_results = pd.DataFrame(results_data)

# Plotting Accuracy vs Recall to visually highlight why SVM wins clinically
plt.figure(figsize=(10, 5))

# Plot Accuracy
plt.plot(
    df_results["Model"],
    df_results["Accuracy"],
    marker="o",
    linewidth=2,
    label="Overall Accuracy",
    color="skyblue",
)
# Plot Recall
plt.plot(
    df_results["Model"],
    df_results["Recall (Class 1)"],
    marker="s",
    linewidth=2,
    label="Recall (Disease Detection)",
    color="salmon",
)

# Formatting the plot
plt.title(
    "The Diagnostic Paradox: Why SVM Wins Clinically Despite kNN's Higher Accuracy",
    fontsize=12,
    fontweight="bold",
    pad=15,
)
plt.ylabel("Score Percentage")
plt.xlabel("Machine Learning Model")
plt.ylim(0.75, 1.0)
plt.grid(axis="y", linestyle="--", alpha=0.7)
plt.legend(loc="lower left")

# Annotate the key insight
plt.annotate(
    "Highest Recall\n(Only 6 Missed Cases)",
    xy=(0, 0.94),
    xytext=(0.2, 0.95),
    arrowprops=dict(facecolor="black", shrink=0.05, width=1, headwidth=6),
)

plt.tight_layout()
plt.show()